### ISSUE TITLE
Change in v3.6.0 tag?

### ISSUE THREAD

**Issue by scpeters** [libbitcoin/libbitcoin-protocol#210]
The libbitcoin* homebrew formulae were updated to use tags named v3.6.0 on 2019-08-09 in https://github.com/Homebrew/homebrew-core/pull/42910, but a recent homebrew build complains that the sha256 of the GitHub archive has changed:

* https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/47556/version=mojave/testReport/junit/brew-test-bot/mojave/fetch___build_from_source_libbitcoin_protocol/

Sometimes this happens on GitHub, but I noticed that the [Github Release page for v3.6.0](https://github.com/libbitcoin/libbitcoin-protocol/releases/tag/v3.6.0) says that the release occurred on 2019-08-29. Was the tag (or tags) changed intentionally?

**Comment by evoskuil** [comment]
@thecodefactory welcome to release control :)

**Comment by thecodefactory** [comment]
@scpeters Mea culpa!  I tagged v3.6.0 a little while ago, but it was missing some recent fixes, and contained the incorrect version number.  After getting that updated, I removed the tags and re-tagged (so yes, intentionally).  I apologize for breaking systems that relied on it.

Knowing this, how bad is the homebrew damage?

@evoskuil Yippee :-)

**Comment by SMillerDev** [comment]
Just the wrong hash. But it's generally better to ask upstream if they meant to do this.

**Comment by thecodefactory** [comment]
> Just the wrong hash. But it's generally better to ask upstream if they meant to do this.

@SMillerDev Got it, thanks!

**Comment by scpeters** [comment]
yeah, it's not the end of the world, and I wanted to confirm that it was an intentional change and not a glitch in GitHub

I've always viewed tags as something that should be permanent, so in the projects I maintain, I always just increment the version number and make a new tag, like 3.6.1 in this case. Just something to think about.

Cheers!
